### ISSUE TITLE
NoneType object has no attribute 'text' issue

### ISSUE THREAD

**Issue by JoeLiu12** [Eben001/IndeedJobScraper#1]
Hey, when I was running the code, it keeps giving me this error code. How can I fix that? Thank you for your code and help!

  File "E:\VS Code\IndeedJobScraper\job_scraper_utils.py", line 72, in scrape_job_data
    job_title = i.find('a', class_="jobTitle_css-1psdjh5_eu4oa1w0").text
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by Eben001** [comment]
Hi, sorry about this. It's been long since I updated this project. 
I'll take out time this weekend to update it. Thanks

**Comment by Eben001** [comment]
That issue has been fixed!
